# -*- coding: utf-8 -*-
"""Aforo2-sesion-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q0GG4q8gv3xCzWmpKM8xoZD6V5xRUdPw
"""

#NO EJECUTAR!!

from google.colab import drive
drive.mount('/content/drive')

"""# A PARTIR DE AQUI EJECUTAR CADA CELDA

##Instalación de dependencias
"""

!pip install ultralytics lapx opencv-python-headless

# 2. VERIFICAR Y CONFIGURAR GPU
import torch
print("=== CONFIGURACIÓN GPU ===")
print(f"CUDA disponible: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU detectada: {torch.cuda.get_device_name(0)}")
    print(f"Memoria GPU total: {torch.cuda.get_device_properties(0).total_memory / 1024**3:.2f} GB")
    device = 'cuda'
else:
    print("⚠️ GPU no disponible. Usando CPU (será más lento)")
    print("Para habilitar GPU: Runtime > Change runtime type > Hardware accelerator > GPU")
    device = 'cpu'
print(f"Dispositivo seleccionado: {device}\n")

print("📦 Instalando ffmpeg...")
!apt-get install -y ffmpeg > /dev/null 2>&1
print("✅ ffmpeg instalado\n")

# 3. IMPORTAR LIBRERÍAS
#from ultralytics import YOLO
import cv2
import os
import numpy as np
from collections import defaultdict
from google.colab import files
import matplotlib.pyplot as plt
from IPython.display import HTML
from base64 import b64encode
from ultralytics import YOLO
import subprocess
import json
import time
from datetime import datetime, timedelta
import pandas as pd
from collections import defaultdict
import re

"""# LEER Y LISTAR LOS ARCHIVOS Y CARPETAS

Aqui se define una función recursiva que recorre todas las carpetas y registra las subcarpetas y los archivos internos.

Para los archivos internos se realiza una clasificacion como sigue:

1. **videos**: Son los archivos a procesar.

2. **Imagen:** Corresponde a la máscara que oculta las zonas del video que no interesan.

3. **JSON:** Contiene las áreas de interés donde se activa el conteo de vehículos. Cada área corresponde a un camino dentro de la intersección, de manera que cada vehículo pasará al menos por dos de estas áreas y la combinación de estas da como resultado el destino que este ha tomado.
"""

def create_directory_tree(path):
    tree = {}

    try:
        # Itera sobre el contenido de la ruta actual
        for item_name in os.listdir(path):
            item_path = os.path.join(path, item_name)

            # Si es un directorio, llama a la función recursivamente
            if os.path.isdir(item_path):
                # La clave es el nombre de la carpeta, el valor es el resultado de la llamada recursiva
                tree[item_name] = {
                        'type': 'folder',
                        'folder': create_directory_tree(item_path)
                    }

            # Si es un archivo, clasifícalo por extensión
            elif os.path.isfile(item_path):
                extension = os.path.splitext(item_name)[1].lower()
                if extension == '.mp4':
                    tree[item_name] = {
                        'type': 'video',
                        'path': item_path,
                        'hora_inicial': item_name.split('_')[1]
                    }
                elif extension == '.png':
                    tree[item_name] = {
                        'type': 'mask',
                        'path': item_path
                    }
                elif extension == '.json':
                    tree[item_name] = {
                        'type': 'zonas_interes',
                        'path': item_path
                    }
                else:
                    tree[item_name] = {
                        'type': 'unknown',
                        'path': item_path
                    } # Marcar como archivo genérico si no coincide

    except FileNotFoundError:
        print(f"Alerta: Ruta no encontrada o acceso denegado: {path}")
        return {} # Devuelve un diccionario vacío en caso de error
    except Exception as e:
        print(f"Error al procesar la ruta {path}: {e}")
        return {}

    return tree

main_folder = "/content/drive/MyDrive/aforo/VIDEOS AV 4 NORTE PARTE 2/VIDEOS_AJUSTADOS"

# Construye el árbol de directorios
directory_tree = create_directory_tree(main_folder)

print("Buscando contenido dentro de la ruta {main_folder}\n")

print("\n**Resultado del Árbol de Directorios (Diccionario):**")
# Imprime el diccionario resultante de forma bonita (formato JSON)
import json
print(directory_tree)

"""#Crear el arbol de archivos

##Recorrer el arbol de documentos para obtener los archivos necesarios
"""

def hora_video(hora_inicial_str: str, video_id: int, duracion_min=24) -> str:
    """
    Calcula la hora de inicio de un video dado un ID y una hora inicial.

    hora_inicial_str: str  -> formato "HH:MM"
    video_id: int          -> id del video (comienza desde 0 o 1)
    duracion_min: int      -> duración del video en minutos
    """
    # Convertir string a objeto datetime
    hora_inicial = datetime.strptime(hora_inicial_str, "%H:%M")

    #La hora inicial esta corrida 24 minutos antes!!
    hora_inicial = hora_inicial - timedelta(minutes = 24)
    # Calcular desplazamiento

    desplazamiento = timedelta(minutes = (video_id - 1) * duracion_min)

    # Sumar desplazamiento
    hora_final = hora_inicial + desplazamiento

    # Devolver como string
    return hora_final.strftime("%H:%M")

def procesar_directorio_recursivo(directory_tree, mask=None, zones=None):
    """
    Procesa recursivamente un árbol de directorios buscando videos y sus
    archivos asociados (mask y zonas_interes).
    """
    video_list = []

    # --- PASO 1: detectar mask y zones de este nivel ---
    local_mask = mask
    local_zones = zones

    for key, value in directory_tree.items():
        if value['type'] == 'mask':
            local_mask = value['path']
            print("Mask encontrada:", value)

        if value['type'] == 'zonas_interes':
            local_zones = value['path']
            print("Zonas encontradas:", value)

    # --- PASO 2: procesar videos y subcarpetas ---
    for key, value in directory_tree.items():

        if value['type'] == 'video':

            full_path = value['path'].replace('/aforo/VIDEOS AV 4 NORTE PARTE 2/', '/aforo/AFORO/RESULTS2/')
            output_folder = os.path.dirname(full_path)

            context = value['path'].replace('/content/drive/MyDrive/aforo/VIDEOS AV 4 NORTE PARTE 2/', '')
            context = os.path.dirname(context)

            output_name = os.path.basename(full_path).replace('.mp4', '_processed.mp4')

            #numeros = re.findall(r'HORARIO\s+(\d+)\s+A\s+(\d+)', full_path)
            #print(numeros)

            #if numeros:
            #inicio, fin = map(int, numeros[0])
            id_video = output_name.split('_')[2]
            #hora_inicial = hora_video(f'{inicio}:00', int(id_video))
            video_list.append({
                'id': id_video,
                'video': value['path'],
                #'hora_inicial': hora_inicial, usar esta si los archivos se obtuvieron desde OS
                'hora_inicial': value['hora_inicial'], # Usar esta si los archivos se obtuvieron desde Google Drive
                'mask': local_mask,
                'zones': local_zones,
                'output_folder': output_folder,
                'output_name': output_name,
                'context_video': context
            })
            #else:
              #raise Exception(f"No se encontró registro de horario para este path: {full_path}")

        if value['type'] == 'folder':
            sub_videos = procesar_directorio_recursivo(
                value['folder'],
                mask=local_mask,
                zones=local_zones
            )
            video_list.extend(sub_videos)

    return video_list



def mostrar_resumen_videos(video_list, minutos_por_video=24):
    """
    Muestra un resumen de los videos encontrados y el tiempo total de procesamiento.

    Args:
        video_list (list): Lista de videos con sus configuraciones
        minutos_por_video (int): Duración promedio de cada video en minutos
    """
    num_videos = len(video_list)
    total_minutos = num_videos * minutos_por_video
    total_horas = total_minutos / 60
    total_dias = total_minutos / 1440

    print("="*70)
    print("📊 RESUMEN DE VIDEOS A PROCESAR")
    print("="*70)
    print(f"📹 Cantidad de videos: {num_videos}")
    print(f"⏱️  Duración por video: {minutos_por_video} minutos")
    print(f"⏰ Tiempo total: {total_horas:.2f} horas ({total_dias:.2f} días)")
    print("="*70)

    # Mostrar detalles de cada video
    return num_videos, total_horas, total_dias

video_list = procesar_directorio_recursivo(directory_tree)

mostrar_resumen_videos(video_list, minutos_por_video=24)
# 2. Mostrar resumen
num, horas, dias = mostrar_resumen_videos(video_list, minutos_por_video=24)

df = pd.DataFrame(video_list)
df_grouped = df.groupby("context_video")

df.to_csv('/content/drive/MyDrive/aforo/AFORO/progreso2.csv', index=False, encoding='utf-8')

"""#Procesamiento del video para el aforo"""

def check_crossing_and_count(track_id, prev_cy, curr_cy, counting_line_y, counted_ids, vehicle_counts, vehicle_type):
    """
    Verifica si un vehículo cruzó la línea de conteo y actualiza los contadores.

    Args:
        track_id (int): ID del objeto rastreado.
        prev_cy (int): Coordenada Y central en el frame anterior.
        curr_cy (int): Coordenada Y central en el frame actual.
        counting_line_y (int): Coordenada Y de la línea de conteo.
        counted_ids (set): Conjunto de IDs ya contados para evitar el doble conteo.
        vehicle_counts (defaultdict): Diccionario de conteos por tipo de vehículo.
        vehicle_type (str): Tipo de vehículo (ej. 'car', 'truck').

    Returns:
        bool: True si el vehículo fue contado, False en caso contrario.
    """
    if track_id not in counted_ids:
        # Condición de cruce hacia abajo: El centro estaba arriba de la línea y ahora está en la línea o debajo
        crossing_down = prev_cy < counting_line_y and curr_cy >= counting_line_y

        # Condición de cruce hacia arriba: El centro estaba debajo de la línea y ahora está en la línea o arriba
        crossing_up = prev_cy > counting_line_y and curr_cy <= counting_line_y

        if crossing_down or crossing_up:
            vehicle_counts[vehicle_type] += 1
            counted_ids.add(track_id)
            return True
    return False

import time
from collections import defaultdict

def contar_vehiculos(video_path, output_folder, max_minutes=None, target_process_fps=5, save_output=True):

    print("\n=== INICIANDO PROCESO ===")
    print(f"🕒 Inicio total: {time.time():.2f}")

    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        print(f"❌ Error al abrir el video: {video_path}")
        return None, None

    fps = int(cap.get(cv2.CAP_PROP_FPS))
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

    # -------------------------------------------------------------------
    # LÓGICA DEL LÍMITE DE TIEMPO (RESTAURADA)
    # -------------------------------------------------------------------
    if max_minutes is None or max_minutes <= 0:
        frames_to_process = total_frames
        print("⏱️ Procesando VIDEO COMPLETO")
    else:
        max_frames = int(fps * 60 * max_minutes)
        frames_to_process = min(max_frames, total_frames)
        print(f"⏱️ Procesando SOLO {max_minutes} minutos → {frames_to_process} frames")

    print(f"Video original: {width}x{height} @ {fps} fps | Total frames: {total_frames}")

    # Frame skipping: fijo en 1 (procesar todos)
    frame_skip_rate = 1

    # -------------------------------------------------------------------
    # ⚡ NUEVO: resolución reducida 50%
    # -------------------------------------------------------------------
    new_width = width // 2
    new_height = height // 2
    counting_line_y = new_height // 2

    print(f"📉 Reducción de resolución a: {new_width}x{new_height}")

    # -------------------------------------------------------------------
    # ⚡ VideoWriter optimizado (FPS reducido)
    # -------------------------------------------------------------------
    out = None
    output_path = None
    OUTPUT_FPS = min(15, fps)  # usar máximo 15 FPS para reducir peso

    if save_output:
        fourcc = cv2.VideoWriter_fourcc(*"mp4v")
        video_name = os.path.basename(video_path).replace(".mp4", "")
        output_path = os.path.join(output_folder, f"{video_name}_reducido.mp4")

        out = cv2.VideoWriter(output_path, fourcc, OUTPUT_FPS, (new_width, new_height))
        if not out.isOpened():
            print("❌ Error al iniciar VideoWriter")
            cap.release()
            return None, None

        print(f"💾 Guardando video reducido en: {output_path}")

    # -------------------------------------------------------------------
    # Estructuras del tracking
    # -------------------------------------------------------------------
    track_history = defaultdict(lambda: [])
    vehicle_counts = defaultdict(int)
    counted_ids = set()

    # -------------------------------------------------------------------
    # INICIO DEL BUCLE PRINCIPAL
    # -------------------------------------------------------------------
    frame_count = 0
    start_time = time.time()

    while cap.isOpened():

        # --- 1) TIEMPO DE LECTURA ---
        t0 = time.time()
        ret, frame = cap.read()
        t_read = time.time() - t0

        if not ret or frame_count >= frames_to_process:
            break

        frame_count += 1

        # Reducir resolución
        frame_resized = cv2.resize(frame, (new_width, new_height), interpolation=cv2.INTER_AREA)

        # --- 2) YOLO ---
        t1 = time.time()
        results = model.track(frame_resized, persist=True, verbose=False, device=device)
        t_yolo = time.time() - t1

        # -------------------------------------------------------------------
        # PROCESAR DETECCIONES
        # -------------------------------------------------------------------
        if results and results[0].boxes.id is not None:
            boxes = results[0].boxes.xyxy.cpu().numpy()
            track_ids = results[0].boxes.id.cpu().numpy().astype(int)
            classes = results[0].boxes.cls.cpu().numpy().astype(int)

            for box, track_id, cls in zip(boxes, track_ids, classes):

                if cls not in VEHICLE_CLASSES:
                    continue

                x1, y1, x2, y2 = box.astype(int)

                cx = (x1 + x2) // 2
                cy = (y1 + y2) // 2

                track_history[track_id].append((cx, cy))

                if len(track_history[track_id]) > 1:
                    prev_cy = track_history[track_id][-2][1]
                    curr_cy = track_history[track_id][-1][1]
                    vehicle_type = VEHICLE_CLASSES[cls]

                    check_crossing_and_count(
                        track_id,
                        prev_cy,
                        curr_cy,
                        counting_line_y,
                        counted_ids,
                        vehicle_counts,
                        vehicle_type
                    )

                # -------------------------------------------------------------------
                # DIBUJAR CAJAS, TEXTOS Y TRAYECTORIAS
                # -------------------------------------------------------------------
                cv2.rectangle(frame_resized, (x1, y1), (x2, y2), (0, 255, 0), 2)

                label = f"{VEHICLE_CLASSES[cls]} ID:{track_id}"
                cv2.putText(frame_resized, label, (x1, y1 - 5),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)

                # trayectoria
                if len(track_history[track_id]) > 2:
                    pts = np.array(track_history[track_id][-20:], dtype=np.int32).reshape((-1, 1, 2))
                    cv2.polylines(frame_resized, [pts], False, (255, 0, 0), 2)

        # -------------------------------------------------------------------
        # DIBUJAR LÍNEA DE CONTEO
        # -------------------------------------------------------------------
        cv2.line(frame_resized, (0, counting_line_y), (new_width, counting_line_y), (0, 255, 255), 2)

        # --- 3) ESCRITURA ---
        if save_output:
            t2 = time.time()
            out.write(frame_resized)
            t_write = time.time() - t2
        else:
            t_write = 0

        # LOG cada 20 frames
        if frame_count % 20 == 0:
            print(
                f"[Frame {frame_count}/{frames_to_process}] "
                f"📥 Lectura: {t_read*1000:.1f} ms | "
                f"🤖 YOLO: {t_yolo*1000:.1f} ms | "
                f"💾 Escritura: {t_write*1000:.1f} ms"
            )

    # -------------------------------------------------------------------
    # CIERRE
    # -------------------------------------------------------------------
    cap.release()
    if save_output:
        out.release()

    print("\n=== FIN DEL PROCESO ===")
    print(f"⏱️ Tiempo total: {time.time() - start_time:.2f} s")
    print(f"Vehículos contados: {sum(vehicle_counts.values())}")

    return output_path, vehicle_counts

# 7. PROCESAR VIDEO
print("\nProcesando video...")

output_video, conteos = contar_vehiculos(
    video_path,
    output_folder,
    max_minutes=2,
    target_process_fps=12, # ¡Cambia este valor para ajustar la velocidad!,
    save_output=True
)

# 8. VISUALIZAR RESULTADOS
# Gráfico de barras
plt.figure(figsize=(10, 6))
tipos = list(conteos.keys())
cantidades = list(conteos.values())
plt.bar(tipos, cantidades, color=['blue', 'green', 'red', 'orange'])
plt.xlabel('Tipo de Vehículo')
plt.ylabel('Cantidad')
plt.title(f'Conteo de Vehículos por Tipo (Primeros {int(3)} minutos)')
plt.grid(axis='y', alpha=0.3)
for i, v in enumerate(cantidades):
    plt.text(i, v + 0.5, str(v), ha='center', fontweight='bold')
plt.show()

"""#Implementación de VehicleCounter class"""

from datetime import datetime, timedelta

class VehicleCounter:

    def __init__(self,
                 model_path,
                 mask_path=None,
                 zones_path=None,
                 reduce_factor=1,
                 device="cpu",
                 output_folder="./output",
                 classes={1: 'bicycle', 2: 'car', 3: 'motorcycle', 5: 'bus', 7: 'truck'},
                 max_minutes=None,
                 verbose=True
                ):
        """
        Inicializa el contador de vehículos.

        Args:
            model_path (str): Ruta al modelo YOLO
            mask_path (str, optional): Ruta a la máscara de región de interés
            zones_path (str, optional): Ruta al JSON con zonas de interés
            reduce_factor (int): Factor de reducción de resolución (1=original, 2=mitad, etc)
            device (str): Dispositivo para YOLO ('cpu', 'cuda', 'mps')
            output_folder (str): Carpeta donde guardar resultados
            max_minutes (int, optional): Límite de minutos a procesar
            verbose (bool): Si True, muestra mensajes de inicialización
        """

        self.verbose = verbose

        # Cargar modelo YOLO
        if self.verbose:
            print("🔄 Cargando modelo YOLO...")
        self.model = YOLO(model_path)
        self.device = device
        if self.verbose:
            print(f"✅ Modelo cargado en: {device}")

        # Configuración
        self.reduce_factor = reduce_factor
        self.output_folder = output_folder
        self.max_minutes = max_minutes
        os.makedirs(self.output_folder, exist_ok=True)

        # Clases de vehículos permitidas
        self.allowed_vehicle_classes = classes
        self.model_names = self.model.names

        # Cargar máscara opcional
        self.mask = None
        if mask_path:
            m = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)
            if m is None:
                if self.verbose:
                    print(f"⚠️ No se pudo leer la máscara: {mask_path}. Se ignorará.")
            else:
                self.mask = m
                if self.verbose:
                    print(f"✅ Máscara cargada: {m.shape}")

        # Cargar zonas de interés
        self.zones = []
        self.zones_original = []
        if zones_path:
            self.set_zones(zones_path)

        # Estado del conteo
        self.vehicle_counts = defaultdict(int)
        self.prev_positions = {}
        self.vehicle_zone_history = {}  # {track_id: [{'zone': 'A', 'timestamp': 1.5}, ...]}
        self.detection_log = []  # Lista para el CSV final

    def set_zones(self, zones_path):
      try:
          with open(zones_path, 'r') as f:
              zones_data = json.load(f)
              self.zones_original = zones_data.get('zones', [])
              if self.verbose:
                  print(f"✅ Zonas cargadas: {len(self.zones_original)} zonas")
                  for zone in self.zones_original:
                      print(f"   - Zona {zone['label']}: {len(zone['points'])} puntos")
      except Exception as e:
          if self.verbose:
              print(f"⚠️ Error al cargar zonas: {e}")


    def scale_zones(self, original_width, original_height, new_width, new_height):
        """
        Escala las coordenadas de las zonas según la resolución de procesamiento.

        Args:
            original_width, original_height: Dimensiones originales del video/imagen
            new_width, new_height: Nuevas dimensiones de procesamiento
        """
        scale_x = new_width / original_width
        scale_y = new_height / original_height

        self.zones = []
        for zone in self.zones_original:
            scaled_points = []
            for point in zone['points']:
                scaled_x = int(point[0] * scale_x)
                scaled_y = int(point[1] * scale_y)
                scaled_points.append([scaled_x, scaled_y])

            self.zones.append({
                'label': zone['label'],
                'points': np.array(scaled_points, dtype=np.int32)
            })

        if self.verbose:
            print(f"🔧 Zonas escaladas de {original_width}x{original_height} a {new_width}x{new_height}")


    def point_in_zone(self, point, zone_points):
        """
        Verifica si un punto está dentro de un polígono (zona).

        Args:
            point: Tupla (x, y)
            zone_points: Array numpy con los puntos del polígono

        Returns:
            bool: True si el punto está dentro de la zona
        """
        return cv2.pointPolygonTest(zone_points, point, False) >= 0


    def calculate_exact_time(self, base_time, elapsed_seconds):
        """
        Calcula la hora exacta sumando el tiempo base del video más los segundos transcurridos.

        Soporta formato de hora base HH:MM o HH:MM:SS.

        Args:
            base_time (str): Hora base en formato HH:MM o HH:MM:SS
            elapsed_seconds (float): Segundos transcurridos desde el inicio del video

        Returns:
            str: Hora exacta en formato HH:MM:SS
        """

        # 1. Determinar el formato y parsear la hora base
        try:
            # Intentar parsear HH:MM:SS
            if len(base_time.split(':')) == 3:
                base_time_format = '%H:%M:%S'
            # Intentar parsear HH:MM
            elif len(base_time.split(':')) == 2:
                base_time_format = '%H:%M'
            else:
                raise ValueError("Formato de base_time inválido. Use HH:MM o HH:MM:SS.")

            # Usamos una fecha ficticia (2000, 1, 1) para manejar solo el tiempo
            base_datetime_str = f"2000-01-01 {base_time}"
            base_datetime = datetime.strptime(base_datetime_str, f"%Y-%m-%d {base_time_format}")

        except ValueError as e:
            if self.verbose:
                print(f"⚠️ Error al parsear base_time '{base_time}': {e}")
            # En caso de error de parseo, retorna None o la base original para evitar fallos.
            return None


        # 2. Sumar los segundos transcurridos
        exact_datetime = base_datetime + timedelta(seconds=elapsed_seconds)

        # 3. Retornar en formato HH:MM:SS
        return exact_datetime.strftime('%H:%M:%S')


    def check_zone_entry(self, track_id, cx, cy, current_time, vehicle_type, base_time=None):
        """
        Verifica si un vehículo entró a alguna zona nueva.

        Args:
            track_id: ID del vehículo
            cx, cy: Coordenadas del centro del vehículo
            current_time: Tiempo actual en segundos
            vehicle_type: Tipo de vehículo
            base_time: Hora base del video en formato HH:MM o HH:MM:SS

        Returns:
            str or None: Label de la zona si entró a una nueva, None en caso contrario
        """
        # Inicializar historial si es la primera vez
        if track_id not in self.vehicle_zone_history:
            self.vehicle_zone_history[track_id] = []

        # Verificar cada zona
        for zone in self.zones:
            zone_label = zone['label']

            # Verificar si está dentro de esta zona
            if self.point_in_zone((cx, cy), zone['points']):

                # Verificar si ya había entrado a esta zona
                already_in_zone = any(
                    entry['zone'] == zone_label
                    for entry in self.vehicle_zone_history[track_id]
                )

                if not already_in_zone:
                    # Calcular hora exacta si se proporciona base_time
                    exact_time = None
                    if base_time:
                        exact_time = self.calculate_exact_time(base_time, current_time)

                    # Nueva entrada a esta zona
                    entry = {
                        'zone': zone_label,
                        'timestamp': current_time,
                        'vehicle_type': vehicle_type
                    }
                    self.vehicle_zone_history[track_id].append(entry)

                    # Agregar al log de detecciones
                    log_entry = {
                        'vehicle_id': track_id,
                        'vehicle_type': vehicle_type,
                        'zone': zone_label,
                        'timestamp_seconds': current_time,
                        'timestamp_formatted': self.format_timestamp(current_time)
                    }

                    # Añadir hora exacta si está disponible
                    if exact_time:
                        log_entry['exact_time'] = exact_time

                    self.detection_log.append(log_entry)

                    return zone_label

        return None


    def format_timestamp(self, seconds):
        """Convierte segundos a formato MM:SS"""
        minutes = int(seconds // 60)
        secs = int(seconds % 60)
        return f"{minutes:02d}:{secs:02d}"


    def filter_detections(self, detections):
        """
        Filtra detecciones para mantener solo vehículos dentro de la máscara.

        Args:
            detections (np.array): Array de detecciones [x1, y1, x2, y2, track_id, cls_id]

        Returns:
            list: Lista de detecciones filtradas
        """
        filtered = []

        for det in detections:
            x1, y1, x2, y2, track_id, cls_id = det
            cls_id_int = int(cls_id)

            # Solo vehículos permitidos
            if cls_id_int not in self.allowed_vehicle_classes:
                continue

            # Centro del bounding box
            cx = int((x1 + x2) / 2)
            cy = int((y1 + y2) / 2)

            # Verificar máscara
            if self.mask is not None:
                if cy >= self.mask.shape[0] or cx >= self.mask.shape[1]:
                    continue
                if self.mask[cy, cx] == 0:
                    continue

            filtered.append(det)

        return filtered


    def draw_zones(self, frame, alpha=0.3):
        """
        Dibuja las zonas de interés en el frame.

        Args:
            frame: Frame de video
            alpha: Transparencia del relleno (0-1)
        """
        overlay = frame.copy()

        # Colores diferentes para cada zona
        colors = [
            (255, 0, 0), (0, 255, 0), (0, 0, 255), (255, 255, 0),
            (255, 0, 255), (0, 255, 255), (128, 0, 128), (255, 128, 0),
            (128, 255, 0)
        ]

        for i, zone in enumerate(self.zones):
            color = colors[i % len(colors)]

            # Dibujar polígono relleno
            cv2.fillPoly(overlay, [zone['points']], color)

            # Dibujar contorno
            cv2.polylines(frame, [zone['points']], True, color, 2)

            # Etiqueta de la zona
            centroid = zone['points'].mean(axis=0).astype(int)
            cv2.putText(frame, zone['label'], tuple(centroid),
                       cv2.FONT_HERSHEY_SIMPLEX, 1.0, (255, 255, 255), 2)

        # Mezclar overlay con frame original
        cv2.addWeighted(overlay, alpha, frame, 1 - alpha, 0, frame)


    def save_detection_log(self, output_path):
        """
        Guarda el log de detecciones en un archivo CSV.

        Args:
            output_path: Ruta del archivo CSV de salida
        """
        import csv

        csv_path = output_path.replace('.mp4', '_detecciones.csv')

        with open(csv_path, 'w', newline='', encoding='utf-8') as f:
            if self.detection_log:
                writer = csv.DictWriter(f, fieldnames=self.detection_log[0].keys())
                writer.writeheader()
                writer.writerows(self.detection_log)

        if self.verbose:
            print(f"📊 Log de detecciones guardado: {csv_path}")

        return csv_path


    def process_video(self, video_path, base_time, output_folder='/content/', output_name="result.mp4", progress_interval=100):
        """
        Procesa un video completo y genera el video con anotaciones.

        Args:
            video_path (str): Ruta al video de entrada
            base_time (str): Hora base del video en formato HH:MM o HH:MM:SS
            output_folder (str): Carpeta donde guardar el resultado
            output_name (str): Nombre del archivo de salida
            progress_interval (int): Cada cuántos frames mostrar progreso

        Returns:
            dict: Diccionario con estadísticas y ruta del CSV
        """

        # Abrir video
        cap = cv2.VideoCapture(video_path)
        if not cap.isOpened():
            raise ValueError(f"❌ No se pudo abrir el video: {video_path}")

        # Propiedades del video
        fps = cap.get(cv2.CAP_PROP_FPS)
        orig_w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        orig_h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
        total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

        # Tamaño de procesamiento
        w = orig_w // self.reduce_factor
        h = orig_h // self.reduce_factor

        # Escalar zonas según el factor de reducción
        if self.zones_original:
            self.scale_zones(orig_w, orig_h, w, h)

        # Redimensionar máscara si existe
        if self.mask is not None:
            self.mask = cv2.resize(self.mask, (w, h), interpolation=cv2.INTER_NEAREST)

        # Calcular frames a procesar
        if self.max_minutes is None or self.max_minutes <= 0:
            frames_to_process = total_frames
            mode_text = "VIDEO COMPLETO"
        else:
            limit_frames = int(self.max_minutes * 60 * fps)
            frames_to_process = min(total_frames, limit_frames)
            mode_text = f"{self.max_minutes} minutos"

        # Configurar salida
        output_path = os.path.join(output_folder, output_name)
        fourcc = cv2.VideoWriter_fourcc(*"mp4v")
        writer = cv2.VideoWriter(output_path, fourcc, fps, (w, h))

        # Variables de control
        frame_index = 0
        start_time = time.time()

        # Mensaje inicial
        if self.verbose:
            print("\n" + "="*70)
            print("🎬 PROCESANDO VIDEO")
            print("="*70)
            print(f"📹 Entrada: {video_path}")
            print(f"💾 Salida: {output_path}")
            print(f"🕐 Hora base: {base_time}")
            print(f"📊 Resolución: {orig_w}x{orig_h} → {w}x{h}")
            print(f"🎯 Frames a procesar: {frames_to_process} ({mode_text})")
            print(f"⚡ FPS: {fps:.1f}")
            print(f"🔷 Zonas de interés: {len(self.zones)}")
            print("="*70)
            print("")

        # Loop principal
        while True:
            ret, frame = cap.read()
            if not ret:
                break
            if frame_index >= frames_to_process:
                break

            # Reducir tamaño
            frame = cv2.resize(frame, (w, h))

            # Tiempo actual en segundos
            current_time = frame_index / fps

            # Detecciones YOLO
            results = self.model.track(
                frame,
                persist=True,
                device=self.device,
                classes=list(self.allowed_vehicle_classes.keys()),
                verbose=False
            )[0]

            # Dibujar zonas de interés
            if self.zones:
                self.draw_zones(frame, alpha=0.2)

            if results.boxes.id is not None:
                # Extraer detecciones
                boxes = results.boxes.xyxy.cpu().numpy()
                ids = results.boxes.id.cpu().numpy().astype(int)
                cls = results.boxes.cls.cpu().numpy().astype(int)

                detections = np.hstack([boxes, ids.reshape(-1, 1), cls.reshape(-1, 1)])

                # Filtrar detecciones
                detections = self.filter_detections(detections)

                # Procesar cada detección
                for det in detections:
                    x1, y1, x2, y2, track_id, cls_id = det
                    cx = int((x1 + x2) / 2)
                    cy = int((y1 + y2) / 2)

                    label = self.allowed_vehicle_classes.get(int(cls_id))

                    # Verificar entrada a zonas (ahora con base_time)
                    entered_zone = self.check_zone_entry(track_id, cx, cy, current_time, label, base_time)

                    # Color según si ya entró a alguna zona
                    has_entries = track_id in self.vehicle_zone_history and len(self.vehicle_zone_history[track_id]) > 0
                    color = (0, 255, 0) if has_entries else (255, 0, 0)

                    # Dibujar
                    cv2.circle(frame, (cx, cy), 5, (0, 255, 255), -1)
                    cv2.rectangle(frame, (int(x1), int(y1)), (int(x2), int(y2)), color, 2)

                    # Mostrar ID y tipo
                    text = f"{label}-{track_id}"
                    cv2.putText(frame, text, (int(x1), int(y1) - 5),
                               cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 2)

                    # Mostrar zonas visitadas
                    if has_entries:
                        zones_visited = [e['zone'] for e in self.vehicle_zone_history[track_id]]
                        zones_text = f"Zonas: {','.join(zones_visited)}"
                        cv2.putText(frame, zones_text, (int(x1), int(y2) + 15),
                                   cv2.FONT_HERSHEY_SIMPLEX, 0.4, (0, 255, 0), 1)

                    self.prev_positions[track_id] = (cx, cy)

            # Mostrar estadísticas en el frame
            y_offset = 30
            cv2.putText(frame, f"Detecciones: {len(self.detection_log)}", (10, y_offset),
                       cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 255), 2)

            y_offset += 30
            cv2.putText(frame, f"Tiempo: {self.format_timestamp(current_time)}", (10, y_offset),
                       cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 255), 2)

            writer.write(frame)
            frame_index += 1

            # Mostrar progreso
            if frame_index % progress_interval == 0:
                elapsed_time = time.time() - start_time
                percent = (frame_index / frames_to_process) * 100
                fps_actual = frame_index / elapsed_time if elapsed_time > 0 else 0
                remaining = (frames_to_process - frame_index) / fps_actual if fps_actual > 0 else 0

                minutes = int(elapsed_time // 60)
                seconds = int(elapsed_time % 60)

                print(f"⏳ {frame_index}/{frames_to_process} frames | "
                      f"{percent:.1f}% | "
                      f"{fps_actual:.1f} FPS | "
                      f"Tiempo: {minutes:02d}:{seconds:02d} | "
                      f"Restante: ~{int(remaining)}s | "
                      f"Detecciones: {len(self.detection_log)}")

        # Liberar recursos
        cap.release()
        writer.release()

        # Guardar CSV
        csv_path = self.save_detection_log(output_path)

        # Mensaje final
        elapsed_total = time.time() - start_time
        if self.verbose:
            print("\n" + "="*70)
            print("✅ PROCESO COMPLETADO")
            print("="*70)
            print(f"⏱️ Tiempo total: {elapsed_total/60:.2f} minutos ({elapsed_total:.0f} segundos)")
            print(f"📁 Video guardado: {output_path}")
            print(f"📊 CSV guardado: {csv_path}")
            print(f"\n🚗 RESUMEN DE DETECCIONES:")
            print(f"   Total de entradas a zonas: {len(self.detection_log)}")

            # Resumen por zona
            zone_counts = defaultdict(int)
            for entry in self.detection_log:
                zone_counts[entry['zone']] += 1

            print(f"\n📍 DETECCIONES POR ZONA:")
            for zone, count in sorted(zone_counts.items()):
                print(f"   Zona {zone}: {count} entradas")

            print("="*70)

        return {
            'video_path': output_path,
            'csv_path': csv_path,
            'total_detections': len(self.detection_log),
            'zone_counts': dict(zone_counts),
            'processing_time': elapsed_total
        }

"""#Ejecución

##Cargar los datos desde la hoja de progreso
"""

!pip install gspread

import gspread
from google.colab import auth
from google.auth import default

def cargar_sheets_a_df(documento_id: str, nombre_pestana: str = "Hoja 1") -> pd.DataFrame:
    """
    Carga datos de una pestaña de Google Sheets a un DataFrame de pandas.

    Args:
        documento_id (str): El ID único del documento de la Hoja de Cálculo.
                           (e.g., el texto entre /d/ y /edit en la URL)
        nombre_pestana (str): El nombre de la pestaña (Worksheet) dentro de la Hoja de Cálculo.

    Returns:
        pd.DataFrame: El DataFrame cargado con los datos de la hoja,
                      o un DataFrame vacío si ocurre un error.
    """
    print("Iniciando autenticación con Google...")

    # --- AUTENTICACIÓN ---
    try:
        auth.authenticate_user()
        creds, _ = default()

        # Autorizar gspread
        gc = gspread.authorize(creds)
        print("✅ Autenticación exitosa.")
    except Exception as e:
        print(f"❌ Error durante la autenticación: {e}")
        return pd.DataFrame()

    # --- ABRIR HOJA DE CÁLCULO POR ID ---
    try:
        spreadsheet = gc.open_by_key(documento_id)
        print(f"Abriendo Hoja de Cálculo: '{spreadsheet.title}'")
    except gspread.SpreadsheetNotFound:
        print(f"❌ Error: No se encontró la Hoja de Cálculo con el ID proporcionado.")
        return pd.DataFrame()

    # --- OBTENER PESTAÑA Y DATOS ---
    try:
        worksheet = spreadsheet.worksheet(nombre_pestana)
        print(f"Pestaña encontrada: '{nombre_pestana}'. Leyendo datos...")

        # Obtener todos los datos como una lista de listas
        # El método get_all_records() lee la primera fila como encabezados automáticamente
        datos = worksheet.get_all_records()

        # Convertir la lista de diccionarios (registros) a DataFrame
        df = pd.DataFrame(datos)

        print(f"✅ Lectura finalizada. Filas cargadas: {len(df)}")
        return df

    except gspread.WorksheetNotFound:
        print(f"❌ Error: La pestaña '{nombre_pestana}' no existe en la Hoja de Cálculo.")
        return pd.DataFrame()
    except Exception as e:
        print(f"❌ Error al leer o convertir los datos: {e}")
        return pd.DataFrame()

"""##Iterar sobre los videos pendientes

Se lee la hoja de calculo y se filtran los registros para ejecutar los procesos con los videos que no tienen progreso en 100%

#Opcional funcion para añadir logs en el archivo principal
"""

def get_or_create_sheet(ss, name):
  try:
        # 1. Intentar obtener la hoja existente
        worksheet = ss.worksheet(name)
        print(f"✅ Pestaña '{name}' obtenida exitosamente.")
        return worksheet

  except gspread.WorksheetNotFound:
        # 2. Si no existe, crear la nueva hoja
        print(f"Pestaña '{name}' no encontrada. Creando nueva pestaña...")
        try:
            worksheet = spreadsheet.add_worksheet(
                title=name, rows=1000, cols=20
            )
            print(f"✅ Pestaña '{name}' creada.")
            return worksheet
        except Exception as e:
            print(f"❌ Error al intentar crear la pestaña: {e}")
            return None

def add_logs_to_file(ss, logs, video):
    """
    Agrega logs al final de una hoja de Google Sheets.
    Si la hoja está vacía, incluye encabezados. Si ya tiene datos, solo agrega las filas.
    Concatena el identificador del video con el valor de la primera columna.

    Args:
        ss: Objeto spreadsheet de gspread
        logs: Lista de diccionarios con los logs
        video: Información del video (video[7] = identificador, video[8] = nombre hoja)
    """
    sheet_name = video[8]
    ws = get_or_create_sheet(ss, sheet_name)

    # Verificar si la hoja está vacía
    all_values = ws.get_all_values()
    is_empty = len(all_values) == 0 or (len(all_values) == 1 and not any(all_values[0]))

    if not logs:
        print(f"⚠️ No hay logs para agregar a la hoja '{sheet_name}'")
        return

    # Obtener el identificador del video
    video_id = video[7]

    # Preparar datos para agregar
    rows_to_add = []

    # Si la hoja está vacía, agregar encabezados (sin modificar)
    if is_empty:
        headers = list(logs[0].keys())
        rows_to_add.append(headers)
        print(f"📋 Agregando encabezados a hoja vacía: {headers}")

    # Agregar todas las filas de logs concatenando video_id a la primera columna
    for log in logs:
        row = list(log.values())
        # Concatenar video_id con el primer valor
        row[0] = f"{video_id}_{row[0]}"
        rows_to_add.append(row)

    # Agregar todas las filas de una vez (más eficiente)
    if rows_to_add:
        ws.append_rows(rows_to_add)

        log_count = len(rows_to_add) - (1 if is_empty else 0)
        print(f"✅ {log_count} logs agregados a la hoja '{sheet_name}' (vehicle_id con prefijo: {video_id})")

    return ws

"""#Iteracion

"""

ID_DE_TU_DOCUMENTO = "17zRVvt1ufAo04fzlDzRjUdoLJh9RzQfiEvlj97P-bkg"
SHEET = "Sheet10"

# --- AUTENTICACIÓN ---
try:
    auth.authenticate_user()
    creds, _ = default()

    # Autorizar gspread
    gc = gspread.authorize(creds)
    print("✅ Autenticación exitosa.")

# --- ABRIR HOJA DE CÁLCULO POR ID ---
    spreadsheet = gc.open_by_key(ID_DE_TU_DOCUMENTO)
    print(f"Abriendo Hoja de Cálculo: '{spreadsheet.title}'")

# --- OBTENER PESTAÑA Y DATOS ---
    ws = spreadsheet.worksheet(SHEET)

    print(f"Hoja abierta: '{ws.title}'")
    all_rows = ws.get_all_values()
    for i, row in enumerate(all_rows):
      #Descartar el encabezado y los videos que ya estan procesados
        if i != 0 and row[0] != '100':
          print( row)
          try:
            counter = None
            #La camara usada aqui tiene una resolucion mas baja, asi que no se debe de aplicar reduccion.
            if 'AV 4 NORTE CON CLL 38 NORTE (SUR)' in row[2]:
              counter = VehicleCounter(
                model_path='yolov8s.pt',
                mask_path=row[4],
                zones_path=row[5],  # Archivo JSON con las zonas
                reduce_factor=1,
                device=device,
                output_folder=row[6],
                max_minutes=None,  # Video completo
                verbose=True
              )
            else:
              counter = VehicleCounter(
                model_path='yolov8s.pt',
                mask_path=row[4],
                zones_path=row[5],  # Archivo JSON con las zonas
                reduce_factor=2,
                device=device,
                output_folder=row[6],
                max_minutes=None,  # Video completo
                verbose=True
              )

            results = counter.process_video(
              video_path=row[2],
              output_name=row[7],
              base_time=row[3],
              output_folder=row[6],
              progress_interval=100
            )
            print(counter.detection_log)
            ws.update_cell(i+1, 1, '100')
            #add_logs_to_file(spreadsheet, counter.detection_log, row)
          except Exception as e:
            ws.update_cell(i+1, 10, 'error')
            print(f"error: {e}")

except Exception as e:
    print(f"❌ Error: Se ha detenido la ejecución: {e}")
else:
    print(f"Se ha finalizado con la ejecución exitosamente")

